import type { WordPack } from '../types';

export const enEasy: WordPack = {
  id: 'en-easy',
  locale: 'en',
  difficulty: 'easy',
  name: 'English · Easy',
  pairs: [
    { id: 'e01', category: 'Transport', civilian: 'Train', undercover: 'Tram' },
    { id: 'e02', category: 'Transport', civilian: 'Bus', undercover: 'Coach' },
    { id: 'e03', category: 'Transport', civilian: 'Car', undercover: 'Taxi' },
    { id: 'e04', category: 'Transport', civilian: 'Bicycle', undercover: 'Motorbike' },
    { id: 'e05', category: 'Transport', civilian: 'Aeroplane', undercover: 'Helicopter' },
    { id: 'e06', category: 'Transport', civilian: 'Boat', undercover: 'Ferry' },
    { id: 'e07', category: 'Places', civilian: 'Beach', undercover: 'Swimming pool' },
    { id: 'e08', category: 'Places', civilian: 'Hospital', undercover: 'Clinic' },
    { id: 'e09', category: 'Places', civilian: 'School', undercover: 'University' },
    { id: 'e10', category: 'Places', civilian: 'Cinema', undercover: 'Theatre' },
    { id: 'e11', category: 'Places', civilian: 'Supermarket', undercover: 'Corner shop' },
    { id: 'e12', category: 'Places', civilian: 'Library', undercover: 'Bookshop' },
    { id: 'e13', category: 'Places', civilian: 'Farm', undercover: 'Zoo' },
    { id: 'e14', category: 'Food & drink', civilian: 'Coffee', undercover: 'Tea' },
    { id: 'e15', category: 'Food & drink', civilian: 'Burger', undercover: 'Sandwich' },
    { id: 'e16', category: 'Food & drink', civilian: 'Pizza', undercover: 'Pie' },
    { id: 'e17', category: 'Food & drink', civilian: 'Chips', undercover: 'Crisps' },
    { id: 'e18', category: 'Food & drink', civilian: 'Milk', undercover: 'Cream' },
    { id: 'e19', category: 'Food & drink', civilian: 'Apple', undercover: 'Pear' },
    { id: 'e20', category: 'Food & drink', civilian: 'Orange', undercover: 'Lemon' },
    { id: 'e21', category: 'Food & drink', civilian: 'Cake', undercover: 'Biscuit' },
    { id: 'e22', category: 'Food & drink', civilian: 'Ice cream', undercover: 'Milkshake' },
    { id: 'e23', category: 'Food & drink', civilian: 'Chocolate', undercover: 'Sweets' },
    { id: 'e24', category: 'Animals', civilian: 'Cat', undercover: 'Tiger' },
    { id: 'e25', category: 'Animals', civilian: 'Dog', undercover: 'Wolf' },
    { id: 'e26', category: 'Animals', civilian: 'Duck', undercover: 'Goose' },
    { id: 'e27', category: 'Animals', civilian: 'Horse', undercover: 'Donkey' },
    { id: 'e28', category: 'Animals', civilian: 'Sheep', undercover: 'Goat' },
    { id: 'e29', category: 'Animals', civilian: 'Dolphin', undercover: 'Shark' },
    { id: 'e30', category: 'Animals', civilian: 'Bee', undercover: 'Butterfly' },
    { id: 'e31', category: 'Technology', civilian: 'Laptop', undercover: 'Tablet' },
    { id: 'e32', category: 'Technology', civilian: 'Zoom', undercover: 'Microsoft Teams' },
    { id: 'e33', category: 'Technology', civilian: 'Email', undercover: 'Text message' },
    { id: 'e34', category: 'Technology', civilian: 'Phone call', undercover: 'Video call' },
    { id: 'e35', category: 'Sport', civilian: 'Football', undercover: 'Rugby' },
    { id: 'e36', category: 'Sport', civilian: 'Tennis', undercover: 'Badminton' },
    { id: 'e37', category: 'Sport', civilian: 'Swimming', undercover: 'Diving' },
    { id: 'e38', category: 'Everyday objects', civilian: 'Pen', undercover: 'Pencil' },
    { id: 'e39', category: 'Everyday objects', civilian: 'Cup', undercover: 'Glass' },
    { id: 'e40', category: 'Everyday objects', civilian: 'Umbrella', undercover: 'Raincoat' },
  ],
};
