import type { WordPack } from '../types';

export const enMedium: WordPack = {
  id: 'en-medium',
  locale: 'en',
  difficulty: 'medium',
  name: 'English · Medium',
  pairs: [
    { id: 'm01', category: 'Places', civilian: 'Park', undercover: 'Garden' },
    { id: 'm02', category: 'Places', civilian: 'Hotel', undercover: 'Hostel' },
    { id: 'm03', category: 'Places', civilian: 'Pub', undercover: 'Bar' },
    { id: 'm04', category: 'Places', civilian: 'Museum', undercover: 'Art gallery' },
    { id: 'm05', category: 'Places', civilian: 'Bridge', undercover: 'Tunnel' },
    { id: 'm06', category: 'Places', civilian: 'Island', undercover: 'Peninsula' },
    { id: 'm07', category: 'Technology', civilian: 'Router', undercover: 'Modem' },
    { id: 'm08', category: 'Technology', civilian: 'Headphones', undercover: 'Earbuds' },
    { id: 'm09', category: 'Technology', civilian: 'Printer', undercover: 'Scanner' },
    { id: 'm10', category: 'Technology', civilian: 'Wi-Fi', undercover: 'Bluetooth' },
    { id: 'm11', category: 'Technology', civilian: 'Password', undercover: 'PIN' },
    { id: 'm12', category: 'Technology', civilian: 'Netflix', undercover: 'YouTube' },
    { id: 'm13', category: 'Food & drink', civilian: 'Pasta', undercover: 'Noodles' },
    { id: 'm14', category: 'Food & drink', civilian: 'Pancake', undercover: 'Waffle' },
    { id: 'm15', category: 'Food & drink', civilian: 'Butter', undercover: 'Margarine' },
    { id: 'm16', category: 'Food & drink', civilian: 'Jam', undercover: 'Marmalade' },
    { id: 'm17', category: 'Food & drink', civilian: 'Cupcake', undercover: 'Muffin' },
    { id: 'm18', category: 'Food & drink', civilian: 'Latte', undercover: 'Cappuccino' },
    { id: 'm19', category: 'Food & drink', civilian: 'Juice', undercover: 'Smoothie' },
    { id: 'm20', category: 'Food & drink', civilian: 'Soup', undercover: 'Stew' },
    { id: 'm21', category: 'Animals', civilian: 'Rabbit', undercover: 'Hare' },
    { id: 'm22', category: 'Animals', civilian: 'Turtle', undercover: 'Tortoise' },
    { id: 'm23', category: 'Animals', civilian: 'Crocodile', undercover: 'Alligator' },
    { id: 'm24', category: 'Animals', civilian: 'Frog', undercover: 'Toad' },
    { id: 'm25', category: 'Entertainment', civilian: 'Violin', undercover: 'Cello' },
    { id: 'm26', category: 'Entertainment', civilian: 'Piano', undercover: 'Keyboard' },
    { id: 'm27', category: 'Entertainment', civilian: 'Guitar', undercover: 'Ukulele' },
    { id: 'm28', category: 'Entertainment', civilian: 'Novel', undercover: 'Short story' },
    { id: 'm29', category: 'Entertainment', civilian: 'Podcast', undercover: 'Radio' },
    { id: 'm30', category: 'Entertainment', civilian: 'Chess', undercover: 'Draughts' },
    { id: 'm31', category: 'Sport', civilian: 'Marathon', undercover: 'Sprint' },
    { id: 'm32', category: 'Sport', civilian: 'Cricket', undercover: 'Baseball' },
    { id: 'm33', category: 'Sport', civilian: 'Skiing', undercover: 'Snowboarding' },
    { id: 'm34', category: 'Sport', civilian: 'Sailing', undercover: 'Rowing' },
    { id: 'm35', category: 'Work & study', civilian: 'Interview', undercover: 'Meeting' },
    { id: 'm36', category: 'Work & study', civilian: 'Resume', undercover: 'Cover letter' },
    { id: 'm37', category: 'Work & study', civilian: 'Teacher', undercover: 'Tutor' },
    { id: 'm38', category: 'Everyday objects', civilian: 'Fridge', undercover: 'Freezer' },
    { id: 'm39', category: 'Everyday objects', civilian: 'Oven', undercover: 'Microwave' },
    { id: 'm40', category: 'Weather', civilian: 'Thunder', undercover: 'Lightning' },
    { id: 'm41', category: 'Roles', civilian: 'Civilian', undercover: 'Undercover' },
    // — New pairs sourced from open-source word lists & web research —
    { id: 'm42', category: 'Food & drink', civilian: 'Chocolate', undercover: 'Vanilla' },
    { id: 'm43', category: 'Food & drink', civilian: 'Beer', undercover: 'Wine' },
    { id: 'm44', category: 'Food & drink', civilian: 'Whiskey', undercover: 'Vodka' },
    { id: 'm45', category: 'Food & drink', civilian: 'Bread', undercover: 'Toast' },
    { id: 'm46', category: 'Food & drink', civilian: 'Chicken', undercover: 'Beef' },
    { id: 'm47', category: 'Food & drink', civilian: 'Salt', undercover: 'Sugar' },
    { id: 'm48', category: 'Food & drink', civilian: 'Honey', undercover: 'Maple syrup' },
    { id: 'm49', category: 'Animals', civilian: 'Mouse', undercover: 'Rat' },
    { id: 'm50', category: 'Animals', civilian: 'Parrot', undercover: 'Crow' },
    { id: 'm51', category: 'Animals', civilian: 'Jellyfish', undercover: 'Octopus' },
    { id: 'm52', category: 'Animals', civilian: 'Wolf', undercover: 'Fox' },
    { id: 'm53', category: 'Animals', civilian: 'Lizard', undercover: 'Gecko' },
    { id: 'm54', category: 'Nature', civilian: 'Volcano', undercover: 'Mountain' },
    { id: 'm55', category: 'Nature', civilian: 'Jungle', undercover: 'Forest' },
    { id: 'm56', category: 'Nature', civilian: 'River', undercover: 'Lake' },
    { id: 'm57', category: 'Nature', civilian: 'Cloud', undercover: 'Fog' },
    { id: 'm58', category: 'Nature', civilian: 'Earthquake', undercover: 'Tsunami' },
    { id: 'm59', category: 'Pop culture', civilian: 'Spiderman', undercover: 'Batman' },
    { id: 'm60', category: 'Pop culture', civilian: 'Superman', undercover: 'Iron Man' },
    { id: 'm61', category: 'Pop culture', civilian: 'Facebook', undercover: 'Instagram' },
    { id: 'm62', category: 'Pop culture', civilian: 'Adidas', undercover: 'Nike' },
    { id: 'm63', category: 'Places', civilian: 'Castle', undercover: 'Palace' },
    { id: 'm64', category: 'Places', civilian: 'Pyramid', undercover: 'Temple' },
    { id: 'm65', category: 'Everyday objects', civilian: 'Candle', undercover: 'Lantern' },
    { id: 'm66', category: 'Everyday objects', civilian: 'Mirror', undercover: 'Window' },
    { id: 'm67', category: 'Everyday objects', civilian: 'Knife', undercover: 'Scissors' },
    { id: 'm68', category: 'Fashion', civilian: 'Socks', undercover: 'Stockings' },
    { id: 'm69', category: 'Fashion', civilian: 'Crown', undercover: 'Hat' },
    { id: 'm70', category: 'Transport', civilian: 'Elevator', undercover: 'Escalator' },
    { id: 'm71', category: 'Transport', civilian: 'Sailboat', undercover: 'Yacht' },
  ],
};
