import type { WordPack } from '../types';

export const enMedium: WordPack = {
  id: 'en-medium',
  locale: 'en',
  difficulty: 'medium',
  name: 'English · Medium',
  pairs: [
    { id: 'm01', category: 'Places', civilian: 'Park', undercover: 'Garden' },
    { id: 'm02', category: 'Places', civilian: 'Hotel', undercover: 'Hostel' },
    { id: 'm03', category: 'Places', civilian: 'Pub', undercover: 'Bar' },
    { id: 'm04', category: 'Places', civilian: 'Museum', undercover: 'Art gallery' },
    { id: 'm05', category: 'Places', civilian: 'Bridge', undercover: 'Tunnel' },
    { id: 'm06', category: 'Places', civilian: 'Island', undercover: 'Peninsula' },
    { id: 'm07', category: 'Technology', civilian: 'Router', undercover: 'Modem' },
    { id: 'm08', category: 'Technology', civilian: 'Headphones', undercover: 'Earbuds' },
    { id: 'm09', category: 'Technology', civilian: 'Printer', undercover: 'Scanner' },
    { id: 'm10', category: 'Technology', civilian: 'Wi-Fi', undercover: 'Bluetooth' },
    { id: 'm11', category: 'Technology', civilian: 'Password', undercover: 'PIN' },
    { id: 'm12', category: 'Technology', civilian: 'Netflix', undercover: 'YouTube' },
    { id: 'm13', category: 'Food & drink', civilian: 'Pasta', undercover: 'Noodles' },
    { id: 'm14', category: 'Food & drink', civilian: 'Pancake', undercover: 'Waffle' },
    { id: 'm15', category: 'Food & drink', civilian: 'Butter', undercover: 'Margarine' },
    { id: 'm16', category: 'Food & drink', civilian: 'Jam', undercover: 'Marmalade' },
    { id: 'm17', category: 'Food & drink', civilian: 'Cupcake', undercover: 'Muffin' },
    { id: 'm18', category: 'Food & drink', civilian: 'Latte', undercover: 'Cappuccino' },
    { id: 'm19', category: 'Food & drink', civilian: 'Juice', undercover: 'Smoothie' },
    { id: 'm20', category: 'Food & drink', civilian: 'Soup', undercover: 'Stew' },
    { id: 'm21', category: 'Animals', civilian: 'Rabbit', undercover: 'Hare' },
    { id: 'm22', category: 'Animals', civilian: 'Turtle', undercover: 'Tortoise' },
    { id: 'm23', category: 'Animals', civilian: 'Crocodile', undercover: 'Alligator' },
    { id: 'm24', category: 'Animals', civilian: 'Frog', undercover: 'Toad' },
    { id: 'm25', category: 'Entertainment', civilian: 'Violin', undercover: 'Cello' },
    { id: 'm26', category: 'Entertainment', civilian: 'Piano', undercover: 'Keyboard' },
    { id: 'm27', category: 'Entertainment', civilian: 'Guitar', undercover: 'Ukulele' },
    { id: 'm28', category: 'Entertainment', civilian: 'Novel', undercover: 'Short story' },
    { id: 'm29', category: 'Entertainment', civilian: 'Podcast', undercover: 'Radio' },
    { id: 'm30', category: 'Entertainment', civilian: 'Chess', undercover: 'Draughts' },
    { id: 'm31', category: 'Sport', civilian: 'Marathon', undercover: 'Sprint' },
    { id: 'm32', category: 'Sport', civilian: 'Cricket', undercover: 'Baseball' },
    { id: 'm33', category: 'Sport', civilian: 'Skiing', undercover: 'Snowboarding' },
    { id: 'm34', category: 'Sport', civilian: 'Sailing', undercover: 'Rowing' },
    { id: 'm35', category: 'Work & study', civilian: 'Interview', undercover: 'Meeting' },
    { id: 'm36', category: 'Work & study', civilian: 'CV', undercover: 'Cover letter' },
    { id: 'm37', category: 'Work & study', civilian: 'Teacher', undercover: 'Tutor' },
    { id: 'm38', category: 'Everyday objects', civilian: 'Fridge', undercover: 'Freezer' },
    { id: 'm39', category: 'Everyday objects', civilian: 'Oven', undercover: 'Microwave' },
    { id: 'm40', category: 'Weather', civilian: 'Thunder', undercover: 'Lightning' },
  ],
};
